sudo: false
language: php
dist: trusty

php:
  - 7.1
  - nightly

env:
  - TRAVIS_NODE_VERSION="8"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - bower_components
    - node_modules
    - vendor

before_install:
  - source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION

install:
  - npm install -g npm@latest
  - npm install -g bower gulp jscs
  - npm install
  - composer self-update && composer --version
  - composer install
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

script:
  - npm run build
  - npm run jshint
  - npm run phpcs
