sudo: false
language: php
php:
  - nightly
  - 5.6
  - 5.5
  - 5.4
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - bower_components

install:
  - npm install -g npm@5.2.0
  - npm install -g bower gulp jscs
  - npm install
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer

script:
  - npm run build
  - npm run jshint
  - phpcs --standard=ruleset.xml --extensions=php -n -s .
