sudo: false
language: php
dist: trusty

php:
  - 7.1
  - nightly

env:
  - TRAVIS_NODE_VERSION="6"
  - TRAVIS_NODE_VERSION="7"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - bower_components

before_install:
  - composer self-update
  - source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION

install:
  - npm install -g npm@5.2.0
  - npm install -g bower gulp jscs
  - npm install
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer

script:
  - npm run build
  - npm run jshint
  - phpcsf --standard=ruleset.xml --extensions=php -n -s .
  - phpcb --standard=ruleset.xml --extensions=php -n -s .
