sudo: false
language: php
dist: trusty

php:
  - 7.1
  - nightly

env:
  - TRAVIS_NODE_VERSION="6"
  - TRAVIS_NODE_VERSION="7"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - bower_components
    - node_modules

before_install:
  - source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION

install:
  - npm install -g npm@latest
  - npm install -g bower gulp jscs
  - npm install
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer

before_script:
  - phpcbf --standard=ruleset.xml --ignore=*/lib/* --extensions=php -s .

script:
  - npm run build
  - npm run jshint
  - phpcs --standard=ruleset.xml --ignore=*/lib/* --colors --extensions=php -n -s .
