version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/php@sha256:0c1e51bca767cd194ad243aed5e9eaac82810582b0a25dccc15fde421421f80c
    steps:
      - checkout
      - run: npm i
      - run: sudo npm install -g bower
      - run: npm test
      - run: curl 'https://api.rollbar.com/api/1/deploy/' -F access_token=bff8e1e90f3449e89e7581c065afe465 -F environment=production -F revision="$CIRCLE_SHA1" -F rollbar_username=ewapettke -F local_username=$CIRCLE_USERNAME -F comment="${CIRCLE_COMPARE_URL}"
