version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: npm i
      - run: sudo -E npm install -g bower
      - run: npm test
      - run: curl 'https://api.rollbar.com/api/1/deploy/' -F access_token=bff8e1e90f3449e89e7581c065afe465 -F environment=production -F revision="$CIRCLE_SHA1" -F rollbar_username=ewapettke -F local_username=$CIRCLE_USERNAME -F comment="${CIRCLE_COMPARE_URL}"
